#!/usr/bin/env bash

# Create a virtualenv if it doesn't already exist.
if [ ! -d orclvenv ]; then
    echo "Creating new virtualenv..."
    virtualenv orclvenv
else
    echo "Found an exisitng virtualenv..."
fi

# Activate the virtualenv
echo "Activating virtualenv..."
source orclvenv/bin/activate

# Attempt to install the required pip dependencies, then touch a file once done.
# If the file already exists only re-run the installation if the requirements file
# is newer than the touched file.
if [ ! -f orclvenv/installed -o requirements.pip -nt orclvenv/installed ]; then

    pip install -r requirements.pip

    if [ $? -ne 0 ]; then
        echo "Unable to install requirements. "
        exit 1
    fi

    touch orclvenv/installed
else
    echo "pip dependencies already installed..."
fi
